name: Release
on:
    push:
        branches: [master, next, main]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: 'Checkout 🧞'
              uses: actions/checkout@v2
            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                  token: ${{ secrets.GH_TOKEN }}
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: npx semantic-release
